version: '3.11'
services:
  jenkins:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.jenkins
    user: "1000:1000"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ../jenkins-data:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
